import os

strings = {
    "values-ar": """    <string name="SpecialForward">تحويل خاص</string>
    <string name="SpecialForwardAbout">تمكين قائمة تحويل متقدمة مع خيارات تحرير وتصفية الرسائل.</string>
    <string name="SpecialForwardTitle">تحويل خاص</string>
    <string name="SpecialForwardEditHint">تعديل الرسالة</string>
    <string name="SpecialForwardResetAll">إعادة تعيين الكل</string>
    <string name="SpecialForwardReplaceAllTexts">استبدال كل النصوص</string>
    <string name="SpecialForwardReplaceAllLinks">استبدال كل الروابط</string>
    <string name="SpecialForwardDeleteAllLinks">حذف كل الروابط</string>
    <string name="SpecialForwardDeleteAllCaptions">حذف جميع تسميات الوسائط</string>
    <string name="SpecialForwardAsFile">تحويل كملف</string>
    <string name="SpecialForwardResetSuccess">تمت إعادة تعيين الرسائل</string>
    <string name="DoubleTapOnChatsToFilterUnread">انقر نقرًا مزدوجًا على الدردشات لتصفية غير المقروءة</string>
    <string name="AmbientMode">الوضع المحيط</string>""",
    "values-es-rES": """    <string name="SpecialForward">Reenvío Especial</string>
    <string name="SpecialForwardAbout">Habilita un menú de reenvío avanzado con opciones de edición y filtrado de mensajes.</string>
    <string name="SpecialForwardTitle">Reenvío especial</string>
    <string name="SpecialForwardEditHint">Editar Mensaje</string>
    <string name="SpecialForwardResetAll">Restablecer todo</string>
    <string name="SpecialForwardReplaceAllTexts">Reemplazar todos los textos</string>
    <string name="SpecialForwardReplaceAllLinks">Reemplazar todos los enlaces</string>
    <string name="SpecialForwardDeleteAllLinks">Eliminar todos los enlaces</string>
    <string name="SpecialForwardDeleteAllCaptions">Eliminar todos los títulos multimedia</string>
    <string name="SpecialForwardAsFile">Reenviar como archivo</string>
    <string name="SpecialForwardResetSuccess">Mensajes restablecidos</string>
    <string name="DoubleTapOnChatsToFilterUnread">Doble toque en chats para filtrar no leídos</string>
    <string name="AmbientMode">Modo Ambiente</string>""",
    "values-fa-rIR": """    <string name="SpecialForward">ارسال ویژه</string>
    <string name="SpecialForwardAbout">فعال کردن منوی پیشرفته ارسال با گزینه‌های ویرایش و فیلتر پیام‌ها.</string>
    <string name="SpecialForwardTitle">ارسال ویژه</string>
    <string name="SpecialForwardEditHint">ویرایش پیام</string>
    <string name="SpecialForwardResetAll">بازنشانی همه</string>
    <string name="SpecialForwardReplaceAllTexts">جایگزینی همه متن‌ها</string>
    <string name="SpecialForwardReplaceAllLinks">جایگزینی همه لینک‌ها</string>
    <string name="SpecialForwardDeleteAllLinks">حذف همه لینک‌ها</string>
    <string name="SpecialForwardDeleteAllCaptions">حذف همه کپشن‌های رسانه</string>
    <string name="SpecialForwardAsFile">ارسال به عنوان فایل</string>
    <string name="SpecialForwardResetSuccess">پیام‌ها بازنشانی شدند</string>
    <string name="DoubleTapOnChatsToFilterUnread">دو بار ضربه روی گفتگوها برای فیلتر خوانده‌نشده‌ها</string>
    <string name="AmbientMode">حالت محیطی</string>""",
    "values-in-rID": """    <string name="SpecialForward">Teruskan Khusus</string>
    <string name="SpecialForwardAbout">Aktifkan menu teruskan lanjutan dengan opsi pengeditan dan pemfilteran pesan.</string>
    <string name="SpecialForwardTitle">Teruskan khusus</string>
    <string name="SpecialForwardEditHint">Edit Pesan</string>
    <string name="SpecialForwardResetAll">Setel ulang semua</string>
    <string name="SpecialForwardReplaceAllTexts">Ganti semua teks</string>
    <string name="SpecialForwardReplaceAllLinks">Ganti semua tautan</string>
    <string name="SpecialForwardDeleteAllLinks">Hapus semua tautan</string>
    <string name="SpecialForwardDeleteAllCaptions">Hapus semua keterangan media</string>
    <string name="SpecialForwardAsFile">Teruskan sebagai file</string>
    <string name="SpecialForwardResetSuccess">Pesan disetel ulang</string>
    <string name="DoubleTapOnChatsToFilterUnread">Ketuk Ganda Pada Obrolan Untuk Memfilter Obrolan Belum Dibaca</string>
    <string name="AmbientMode">Mode Ambien</string>""",
    "values-it-rIT": """    <string name="SpecialForward">Inoltro Speciale</string>
    <string name="SpecialForwardAbout">Abilita un menu di inoltro avanzato con opzioni di modifica e filtraggio dei messaggi.</string>
    <string name="SpecialForwardTitle">Inoltro speciale</string>
    <string name="SpecialForwardEditHint">Modifica Messaggio</string>
    <string name="SpecialForwardResetAll">Ripristina tutto</string>
    <string name="SpecialForwardReplaceAllTexts">Sostituisci tutti i testi</string>
    <string name="SpecialForwardReplaceAllLinks">Sostituisci tutti i link</string>
    <string name="SpecialForwardDeleteAllLinks">Elimina tutti i link</string>
    <string name="SpecialForwardDeleteAllCaptions">Elimina tutte le didascalie dei media</string>
    <string name="SpecialForwardAsFile">Inoltra come file</string>
    <string name="SpecialForwardResetSuccess">Messaggi ripristinati</string>
    <string name="DoubleTapOnChatsToFilterUnread">Doppio tocco sulle chat per filtrare le non lette</string>
    <string name="AmbientMode">Modalità Ambiente</string>""",
    "values-ja-rJP": """    <string name="SpecialForward">特別な転送</string>
    <string name="SpecialForwardAbout">メッセージの編集とフィルタリングオプションを備えた高度な転送メニューを有効にします。</string>
    <string name="SpecialForwardTitle">特別な転送</string>
    <string name="SpecialForwardEditHint">メッセージを編集</string>
    <string name="SpecialForwardResetAll">すべてリセット</string>
    <string name="SpecialForwardReplaceAllTexts">すべてのテキストを置換</string>
    <string name="SpecialForwardReplaceAllLinks">すべてのリンクを置換</string>
    <string name="SpecialForwardDeleteAllLinks">すべてのリンクを削除</string>
    <string name="SpecialForwardDeleteAllCaptions">すべてのメディアキャプションを削除</string>
    <string name="SpecialForwardAsFile">ファイルとして転送</string>
    <string name="SpecialForwardResetSuccess">メッセージがリセットされました</string>
    <string name="DoubleTapOnChatsToFilterUnread">チャットをダブルタップして未読をフィルタリング</string>
    <string name="AmbientMode">アンビエントモード</string>""",
    "values-pl-rPL": """    <string name="SpecialForward">Specjalne przekazywanie</string>
    <string name="SpecialForwardAbout">Włącz zaawansowane menu przekazywania z opcjami edycji i filtrowania wiadomości.</string>
    <string name="SpecialForwardTitle">Specjalne przekazywanie</string>
    <string name="SpecialForwardEditHint">Edytuj wiadomość</string>
    <string name="SpecialForwardResetAll">Zresetuj wszystko</string>
    <string name="SpecialForwardReplaceAllTexts">Zamień wszystkie teksty</string>
    <string name="SpecialForwardReplaceAllLinks">Zamień wszystkie linki</string>
    <string name="SpecialForwardDeleteAllLinks">Usuń wszystkie linki</string>
    <string name="SpecialForwardDeleteAllCaptions">Usuń wszystkie podpisy multimediów</string>
    <string name="SpecialForwardAsFile">Przekaż jako plik</string>
    <string name="SpecialForwardResetSuccess">Wiadomości zresetowane</string>
    <string name="DoubleTapOnChatsToFilterUnread">Kliknij dwukrotnie czaty, aby przefiltrować nieprzeczytane</string>
    <string name="AmbientMode">Tryb Ambient</string>""",
    "values-pt-rBR": """    <string name="SpecialForward">Encaminhamento Especial</string>
    <string name="SpecialForwardAbout">Ative um menu de encaminhamento avançado com opções de edição e filtragem de mensagens.</string>
    <string name="SpecialForwardTitle">Encaminhamento especial</string>
    <string name="SpecialForwardEditHint">Editar Mensagem</string>
    <string name="SpecialForwardResetAll">Redefinir tudo</string>
    <string name="SpecialForwardReplaceAllTexts">Substituir todos os textos</string>
    <string name="SpecialForwardReplaceAllLinks">Substituir todos os links</string>
    <string name="SpecialForwardDeleteAllLinks">Excluir todos os links</string>
    <string name="SpecialForwardDeleteAllCaptions">Excluir todas as legendas de mídia</string>
    <string name="SpecialForwardAsFile">Encaminhar como arquivo</string>
    <string name="SpecialForwardResetSuccess">Mensagens redefinidas</string>
    <string name="DoubleTapOnChatsToFilterUnread">Toque duplo nos chats para filtrar não lidos</string>
    <string name="AmbientMode">Modo Ambiente</string>""",
    "values-ru-rRU": """    <string name="SpecialForward">Специальная пересылка</string>
    <string name="SpecialForwardAbout">Включить расширенное меню пересылки с опциями редактирования и фильтрации.</string>
    <string name="SpecialForwardTitle">Специальная пересылка</string>
    <string name="SpecialForwardEditHint">Редактировать сообщение</string>
    <string name="SpecialForwardResetAll">Сбросить всё</string>
    <string name="SpecialForwardReplaceAllTexts">Заменить все тексты</string>
    <string name="SpecialForwardReplaceAllLinks">Заменить все ссылки</string>
    <string name="SpecialForwardDeleteAllLinks">Удалить все ссылки</string>
    <string name="SpecialForwardDeleteAllCaptions">Удалить все подписи медиа</string>
    <string name="SpecialForwardAsFile">Переслать как файл</string>
    <string name="SpecialForwardResetSuccess">Сообщения сброшены</string>
    <string name="DoubleTapOnChatsToFilterUnread">Двойное нажатие на чаты для фильтрации непрочитанных</string>
    <string name="AmbientMode">Режим Ambient</string>""",
    "values-tr-rTR": """    <string name="SpecialForward">Özel İletme</string>
    <string name="SpecialForwardAbout">Mesaj düzenleme ve filtreleme seçenekleriyle gelişmiş bir iletme menüsünü etkinleştirin.</string>
    <string name="SpecialForwardTitle">Özel iletme</string>
    <string name="SpecialForwardEditHint">Mesajı Düzenle</string>
    <string name="SpecialForwardResetAll">Tümünü sıfırla</string>
    <string name="SpecialForwardReplaceAllTexts">Tüm metinleri değiştir</string>
    <string name="SpecialForwardReplaceAllLinks">Tüm bağlantıları değiştir</string>
    <string name="SpecialForwardDeleteAllLinks">Tüm bağlantıları sil</string>
    <string name="SpecialForwardDeleteAllCaptions">Tüm medya altyazılarını sil</string>
    <string name="SpecialForwardAsFile">Dosya olarak ilet</string>
    <string name="SpecialForwardResetSuccess">Mesajlar sıfırlandı</string>
    <string name="DoubleTapOnChatsToFilterUnread">Okunmayanları Filtrelemek İçin Sohbetlere Çift Dokunun</string>
    <string name="AmbientMode">Ortam Modu</string>""",
    "values-uk-rUA": """    <string name="SpecialForward">Спеціальне пересилання</string>
    <string name="SpecialForwardAbout">Увімкнути розширене меню пересилання з параметрами редагування та фільтрації повідомлень.</string>
    <string name="SpecialForwardTitle">Спеціальне пересилання</string>
    <string name="SpecialForwardEditHint">Редагувати повідомлення</string>
    <string name="SpecialForwardResetAll">Скинути все</string>
    <string name="SpecialForwardReplaceAllTexts">Замінити всі тексти</string>
    <string name="SpecialForwardReplaceAllLinks">Замінити всі посилання</string>
    <string name="SpecialForwardDeleteAllLinks">Видалити всі посилання</string>
    <string name="SpecialForwardDeleteAllCaptions">Видалити всі підписи медіа</string>
    <string name="SpecialForwardAsFile">Переслати як файл</string>
    <string name="SpecialForwardResetSuccess">Повідомлення скинуто</string>
    <string name="DoubleTapOnChatsToFilterUnread">Подвійне натискання на чати для фільтрації непрочитаних</string>
    <string name="AmbientMode">Режим Ambient</string>""",
    "values-zh-rCN": """    <string name="SpecialForward">特殊转发</string>
    <string name="SpecialForwardAbout">启用具有消息编辑和过滤选项的高级转发菜单。</string>
    <string name="SpecialForwardTitle">特殊转发</string>
    <string name="SpecialForwardEditHint">编辑消息</string>
    <string name="SpecialForwardResetAll">全部重置</string>
    <string name="SpecialForwardReplaceAllTexts">替换所有文本</string>
    <string name="SpecialForwardReplaceAllLinks">替换所有链接</string>
    <string name="SpecialForwardDeleteAllLinks">删除所有链接</string>
    <string name="SpecialForwardDeleteAllCaptions">删除所有媒体标题</string>
    <string name="SpecialForwardAsFile">作为文件转发</string>
    <string name="SpecialForwardResetSuccess">消息已重置</string>
    <string name="DoubleTapOnChatsToFilterUnread">双击聊天列表以过滤未读聊天</string>
    <string name="AmbientMode">环境模式</string>""",
    "values-zh-rTW": """    <string name="SpecialForward">特殊轉發</string>
    <string name="SpecialForwardAbout">啟用具有訊息編輯和過濾選項的進階轉發選單。</string>
    <string name="SpecialForwardTitle">特殊轉發</string>
    <string name="SpecialForwardEditHint">編輯訊息</string>
    <string name="SpecialForwardResetAll">全部重置</string>
    <string name="SpecialForwardReplaceAllTexts">替換所有文字</string>
    <string name="SpecialForwardReplaceAllLinks">替換所有連結</string>
    <string name="SpecialForwardDeleteAllLinks">刪除所有連結</string>
    <string name="SpecialForwardDeleteAllCaptions">刪除所有媒體標題</string>
    <string name="SpecialForwardAsFile">作為檔案轉發</string>
    <string name="SpecialForwardResetSuccess">訊息已重置</string>
    <string name="DoubleTapOnChatsToFilterUnread">雙擊聊天列表以過濾未讀聊天</string>
    <string name="AmbientMode">環境模式</string>"""
}

base_dir = r"D:\Alexgram\TMessagesProj\src\main\res"

for lang, new_strings in strings.items():
    file_path = os.path.join(base_dir, lang, "strings_nax.xml")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        
        if 'name="SpecialForward"' not in content:
            insert_text = "\n" + new_strings + "\n"
            content = content.replace("</resources>", f"{insert_text}</resources>")
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Updated {lang}")
        else:
            print(f"Skipped {lang} (already updated)")
    else:
        print(f"File not found: {file_path}")
